# logo: Donkey # add logo name
logo: logo.png # add logo name
title: Donkey - Enjoy Travel
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl:
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: banner.jpg #mountains.mp4 #waterfall.mov #mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: Enjoy Travel # add banner title
banner-desc: # add banner description

# Author settings
author-pic: avatar3.jpg # your photo
author-name: Irene
about-author: Enjoy Travel
email: info@donkeytravel.eu # your email
phone:
website: https://www.donkeytravel.eu # you website

# Social link
# google_url:    # add url link
twitter_url: https://twitter.com/donkey_travel # add url link
instagram_url: # add url link
# pinterest_url: # add url link
# dribbble_url:  # add url link
facebook_url:  # add url link

# Disqus
discus_identifier: donkeytravel # add your discus identifier.  Not your username.  To get this, register your forum here with a unique ID: https://disqus.com/admin/create/

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

gems:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
