# logo: Donkey # add logo name
logo: donkey-logo-dark.png # add logo name
title: Donkey Travel - Ταξιδιωτικές εμπειρίες
description: > # this means to ignore newlines until "baseurl:"
  The journey is born in our mind and grows to our heart!
permalink: '/blog/:title/'
baseurl:
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains #banner.jpg #mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: Enjoy Travel # add banner title
banner-desc: "\"Of all the paths you take in life, make sure a few of them are dirt.\"<br> -JOHN MUIR"

# Author settings
author-pic: avatar3.jpg # your photo
author-name: Irene
about-author: "Hi, I am Irene, the author of Travel Donkey, the blog you're currently viewing. <br>I hope you like it!"
email: info@donkeytravel.eu # your email
phone:
website: https://www.donkeytravel.eu # you website

# Social link
# google_url:    # add url link
twitter_url: https://twitter.com/donkey_travel # add url link
instagram_url: https://www.instagram.com/donkeytravelworld
youtube_url: https://www.youtube.com/channel/UC2pbm3MeIF3F7IYQkILttcA
# pinterest_url: # add url link
# dribbble_url:  # add url link
facebook_url:  # add url link

# Disqus
discus_identifier: donkeytravel # add your discus identifier.  Not your username.  To get this, register your forum here with a unique ID: https://disqus.com/admin/create/

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics: UA-166912300-1

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

gems:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
